---
title: "EE_DVcalc_update"
author: "Ben Wells"
date: "`r Sys.Date()`"
output: html_document
---

```{r label="get_aqs_data",echo=FALSE,message=FALSE,warning=FALSE}
aqs.userid <- Sys.getenv("AQS_userid")
aqs.passwd <- Sys.getenv("AQS_passwd")
get.aqs.data <- function(sql) {
  require(ROracle)
  driver <- dbDriver("Oracle")
  db <- "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=db-api.aqs.epa.gov)(PORT=1521))(CONNECT_DATA=(SID=thor)))"
  con <- dbConnect(driver,username=aqs.userid,password=aqs.passwd,dbname=db)
  aqs.data <- dbGetQuery(con,sql)
  colnames(aqs.data) <- tolower(colnames(aqs.data))
  dbDisconnect(con)
  return(aqs.data)
}
```

```{r label="get_unique_dates",echo=FALSE,message=FALSE,warning=FALSE}
## Function to get earliest or latest date values by monitor
## dt = column with date or datetime values
## id = monitor id variable
## first = use earliest value (TRUE) or latest value (FALSE)?
get.unique.dates <- function(dt,id,first) {
  if (any(dt == " ")) { dt[which(dt == " ")] <- as.character(Sys.Date()) }
  if (first) { unique.dates <- tapply(dt,list(id),min) }
  if (!first) { unique.dates <- tapply(dt,list(id),max) }
  out <- sapply(unique.dates,function(x) ifelse(x == Sys.Date(),
    " ",as.character(x)))
  return(out)
}
```

```{r label="get_unique_codes",echo=FALSE,message=FALSE,warning=FALSE}
## Function to get codes associated with most recent begin dates
## dt = column with date or datetime values
## id = monitor id variable
## code = column with code values
get.unique.codes <- function(dt,id,code) {
  ids <- unique(id)
  n <- length(ids)
  out <- rep(" ",n)
  for (i in 1:n) {
    t <- which(id == ids[i])
    if (length(t) == 1) {
      out[i] <- code[t]
      next
    }
    if (any(dt[t] == " ")) {
      j <- which(dt[t] == " ")[1]
      out[i] <- code[t][j]
      next
    }
    out[i] <- code[t][which.max(as.Date(dt[t]))]
  }    
  return(out)
}
```

```{r label="get_methods",echo=FALSE,message=FALSE,warning=FALSE}
## Function to get all method codes associated with a given pollutant
get.methods <- function(par) {
  methods <- get.aqs.data(paste("SELECT DISTINCT
    methods.methodology_code AS method_code,
    COALESCE(methods.reference_method_id,' ') AS frm_fem_id,
    COALESCE(methods.sample_anal_desc,' ') AS method_desc,
    COALESCE(methods.equivalent_method_desc,' ') AS manufacturer,
    methods.fed_mdl AS mdl
    FROM sampling_methodologies methods
   WHERE methods.pa_parameter_code = '",par,"'
     AND methods.status_ind = 'P'
   ORDER BY 1",sep=""))
  methods$mdl <- as.numeric(methods$mdl)*ifelse(par == 44201,1000,1)
  if (par == 44201) { 
    ## Fix issue with AIRS legacy FRM method code
    methods$frm_fem_id[which(methods$method_code == '011')] <- "RFOA-0176-011"
    methods$manufacturer[which(methods$method_code == '011')] <- "AIRS LEGACY CODE"
  }
  return(methods)
}
```

```{r label="get_seasons",echo=FALSE,message=FALSE,warning=FALSE}
## Function to get ozone monitoring seasons for a range of years
## yr1 = get seasons with begin dates on or after this year
## yr2 = get seasons with end dates on or before this year
get.seasons <- function(yr1,yr2) {
  seasons <- get.aqs.data(paste("SELECT DISTINCT
        COALESCE(seasons.cn_stt_state_code,' ') as state,
        COALESCE(seasons.cn_county_code,' ') as county,
        COALESCE(seasons.site_id,' ') as site_id,
        COALESCE(seasons.monitoring_season_begin_month,1) as begin_month,
        COALESCE(seasons.monitoring_season_begin_day,1) as begin_day,
        COALESCE(seasons.monitoring_season_begin_year,",yr1,") as begin_year,
        COALESCE(seasons.monitoring_season_end_month,12) as end_month,
        COALESCE(seasons.monitoring_season_end_day,31) as end_day,
        COALESCE(seasons.monitoring_season_end_year,",yr2,") as end_year
   FROM monitoring_seasons seasons
  WHERE seasons.pa_parameter_code = '44201'
    AND seasons.monitoring_season_begin_year <= '",yr2,"'
    AND (seasons.monitoring_season_end_year >= '",yr1,"'
     OR seasons.monitoring_season_end_year IS NULL)
    AND seasons.cn_stt_state_code NOT IN ('80','CC')
  ORDER BY 1,2,3",sep=""))
  return(seasons)
}
```

```{r label="get_monitors",echo=FALSE,message=FALSE,warning=FALSE}
## Function to retrieve monitor metadata from AQS
## par = Get monitors with this AQS parameter code
## yr1 = Get monitors stopping after/during this year
## yr2 = Get monitors starting before/during this year
## all = Return all results (TRUE) or unique ids only (FALSE)?
get.monitors <- function(par,yr1,yr2,all=FALSE) {
  poll.table <- get.aqs.data(paste("SELECT DISTINCT
    psids.pollutant_standard_id AS psid,
    psids.pa_parameter_code AS par,
    psids.short_description AS standard
    FROM pollutant_standards psids
    WHERE psids.pa_parameter_code = '",par,"'
      AND psids.pollutant_standard_id NOT IN (3,5,6,7,18,21,24)
    ORDER BY 1,2",sep=""))
  poll.table$year <- sapply(poll.table$standard,function(x) substr(x,nchar(x)-3,nchar(x)))
  if (par == 12128) { poll.table$year <- 2009 }
  if (par == 88101) { poll.table$psid[3] <- 18 }
  t <- get.aqs.data(paste("SELECT DISTINCT
    sites.state_code || sites.county_code || sites.site_id || monitors.poc AS id,
    COALESCE(INITCAP(sites.local_site_name),' ') AS site_name,
    COALESCE(INITCAP(sites.street_address),' ') AS address,
    ROUND(COALESCE(sites.standard_latitude,sites.user_latitude),6) AS latitude,
    ROUND(COALESCE(sites.standard_longitude,sites.user_longitude),6) AS longitude,
    tz.gmt_diff AS gmt_offset,
    TO_NUMBER(regions.epa_region_code,'99') AS epa_region,
    states.state_name AS state_name,
    counties.county_name AS county_name,
    COALESCE(TRIM(cbsas.cbsa_name),' ') AS cbsa_name,
    COALESCE(TRIM(cbsas.csa_title),' ') AS csa_name,",
    if (nrow(poll.table) > 0) { 
      paste("COALESCE(
        (SELECT area_name || ', ' || state_suffix
           FROM site_naa
          WHERE sites.si_id = site_naa.si_id(+)
            AND parameter_code = '",poll.table$par[1],"'
            AND ps_id = '",poll.table$psid[1],"'),' ')
        AS naa_name_",poll.table$year[1],",",sep="")
    },
    if (nrow(poll.table) > 1) { 
      paste("COALESCE(
        (SELECT area_name || ', ' || state_suffix
           FROM site_naa
          WHERE sites.si_id = site_naa.si_id(+)
            AND parameter_code = '",poll.table$par[2],"'
            AND ps_id = '",poll.table$psid[2],"'),' ')
        AS naa_name_",poll.table$year[2],",",sep="")
    },
    if (nrow(poll.table) > 2) { 
      paste("COALESCE(
        (SELECT area_name || ', ' || state_suffix
           FROM site_naa
          WHERE sites.si_id = site_naa.si_id(+)
            AND parameter_code = '",poll.table$par[3],"'
            AND ps_id = '",poll.table$psid[3],"'),' ')
        AS naa_name_",poll.table$year[3],",",sep="")
    },
    if (nrow(poll.table) > 3) { 
      paste("COALESCE(
        (SELECT area_name || ', ' || state_suffix
           FROM site_naa
          WHERE sites.si_id = site_naa.si_id(+)
            AND parameter_code = '",poll.table$par[4],"'
            AND ps_id = '",poll.table$psid[4],"'),' ')
        AS naa_name_",poll.table$year[4],",",sep="")
    },
    "COALESCE(agencies.agency_desc,' ') AS reporting_agency,
    COALESCE(INITCAP(monitors.ms_measurement_scale),' ') AS measurement_scale,
    COALESCE(INITCAP(objectives.mot_monitor_obj_type),' ') AS monitor_objective,
    COALESCE(TO_CHAR(sp.sampling_begin_date+1/24,'YYYY-MM-DD'),' ') AS monitor_begin_date,
    COALESCE(TO_CHAR(sp.sampling_end_date+1/24,'YYYY-MM-DD'),' ') AS monitor_end_date,
    COALESCE(TO_CHAR(monitors.last_sampling_date+1/24,'YYYY-MM-DD'),' ') AS last_sample_date,
    COALESCE(TO_CHAR(exclusions.begin_date+1/24,'YYYY-MM-DD'),' ') AS nonreg_begin_date,
    COALESCE(TO_CHAR(exclusions.end_date+1/24,'YYYY-MM-DD'),' ') AS nonreg_end_date,
    COALESCE(exclusions.concurrence_flag,' ') AS nonreg_concur,
    COALESCE(methods.method_code,' ') AS method_code,
    COALESCE(sm.reference_method_id,' ') AS frm_code,
    COALESCE(TO_CHAR(methods.begin_date+1/24,'YYYY-MM-DD'),' ') AS method_begin_date,
    COALESCE(TO_CHAR(methods.end_date+1/24,'YYYY-MM-DD'),' ') AS method_end_date,
    COALESCE(mta.mt_monitor_type,' ') AS monitor_type,
    COALESCE(TO_CHAR(mta.monitor_type_begin_date+1/24,'YYYY-MM-DD'),' ') AS type_begin_date,
    COALESCE(TO_CHAR(mta.monitor_type_end_date+1/24,'YYYY-MM-DD'),' ') AS type_end_date,
    COALESCE(mna.monitor_network_code,' ') AS network,
    COALESCE(TO_CHAR(mna.begin_date+1/24,'YYYY-MM-DD'),' ') AS network_begin_date,
    COALESCE(TO_CHAR(mna.end_date+1/24,'YYYY-MM-DD'),' ') AS network_end_date,
    COALESCE(TO_CHAR(pmp.begin_date+1/24,'YYYY-MM-DD'),' ') AS primary_begin_date,
    COALESCE(TO_CHAR(pmp.end_date+1/24,'YYYY-MM-DD'),' ') AS primary_end_date,
    COALESCE(INITCAP(cf.coll_freq_desc),' ') AS collection_frequency,
    COALESCE(TO_CHAR(rcf.req_coll_freq_begin_date+1/24,'YYYY-MM-DD'),' ') AS frequency_begin_date,
    COALESCE(TO_CHAR(rcf.req_coll_freq_end_date+1/24,'YYYY-MM-DD'),' ') AS frequency_end_date,
    COALESCE(combos.second_site_state || combos.second_site_county || 
      combos.second_site_number,' ') AS combo_site,
    COALESCE(TO_CHAR(combos.cutover_date+1/24,'YYYY-MM-DD'),' ') AS combo_date,
    COALESCE(seasons.monitoring_season_begin_year,",yr1,") || '-' ||
      COALESCE(TO_CHAR(seasons.monitoring_season_begin_month,'FM09'),'01') || '-' ||
      COALESCE(TO_CHAR(seasons.monitoring_season_begin_day,'FM09'),'01') AS season_begin_date,
    COALESCE(seasons.monitoring_season_end_year,",yr2,") || '-' ||
      COALESCE(TO_CHAR(seasons.monitoring_season_end_month,'FM09'),'12') || '-' ||
      COALESCE(TO_CHAR(seasons.monitoring_season_end_day,'FM09'),'31') AS season_end_date
  FROM agencies agencies,
    cbsa_mapping cbsas,
    collection_frequencies cf,
    counties counties,
    epa_regions regions,
    linked_sites combos,
    measurement_scales scales,
    monitor_exclusions exclusions,
    monitor_methods methods,
    monitor_networks networks,
    monitor_network_affiliations mna,
    monitor_objectives objectives,
    monitor_objective_types mot,
    monitor_types types,
    monitor_type_assignments mta,
    monitoring_seasons seasons,
    monitors monitors,
    primary_monitor_periods pmp,
    req_coll_frequencies rcf,
    sample_periods sp,
    sampling_methodologies sm,
    site_basic sites,
    site_time_zone stz,
    states states,
    time_zones tz
  WHERE agencies.agency_code = monitors.monitoring_agency
    AND methods.method_code = sm.methodology_code
    AND methods.parameter_code = sm.pa_parameter_code
    AND mna.monitor_network_code = networks.monitor_network_code(+)
    AND monitors.mo_id = exclusions.mo_id(+)
    AND monitors.mo_id = methods.mo_id(+)
    AND monitors.mo_id = mna.mo_id(+)
    AND monitors.mo_id = mta.mo_mo_id(+)
    AND monitors.mo_id = objectives.mo_mo_id(+)
    AND monitors.mo_id = pmp.mo_id(+)
    AND monitors.mo_id = rcf.mo_mo_id(+)
    AND monitors.mo_id = sp.mo_mo_id(+)
    AND monitors.ms_measurement_scale = scales.measurement_scale(+)
    AND monitors.si_si_id = sites.si_id
    AND mta.mt_monitor_type = types.monitor_type(+)
    AND objectives.mot_monitor_obj_type = mot.monitor_obj_type(+)
    AND rcf.cf_coll_freq_code = cf.coll_freq_code(+)
    AND regions.epa_region_code = states.epar_epa_region_code
    AND sites.county_code = cbsas.county_code(+)
    AND sites.county_code = counties.county_code
    AND sites.si_id = combos.first_si_id(+)
    AND sites.state_code = cbsas.state_code(+)
    AND sites.state_code = counties.stt_state_code
    AND sites.state_code = states.state_code
    AND stz.si_id = sites.si_id
    AND tz.time_zone_name = stz.time_zone_name
    AND combos.parameter_code(+) = '",par,"'
    AND EXTRACT(YEAR FROM combos.cutover_date(+)) >= '",yr1,"'
    AND EXTRACT(YEAR FROM combos.cutover_date(+)) <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM exclusions.begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM exclusions.end_date(+)),",yr2,") >= '",yr1,"'
    AND COALESCE(EXTRACT(YEAR FROM methods.begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM methods.end_date(+)),",yr2,") >= '",yr1,"'
    AND COALESCE(EXTRACT(YEAR FROM mna.begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM mna.end_date(+)),",yr2,") >= '",yr1,"'
    AND COALESCE(EXTRACT(YEAR FROM monitors.last_sampling_date),",yr2,") >= '",yr1,"'
    AND monitors.last_sampling_date IS NOT NULL
    AND monitors.pa_parameter_code = '",par,"'
    AND monitors.status_ind = 'P'
    AND COALESCE(EXTRACT(YEAR FROM mta.monitor_type_begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM mta.monitor_type_end_date(+)),",yr2,") >= '",yr1,"'
    AND COALESCE(EXTRACT(YEAR FROM pmp.begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM pmp.end_date(+)),",yr2,") >= '",yr1,"'
    AND COALESCE(EXTRACT(YEAR FROM rcf.req_coll_freq_begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM rcf.req_coll_freq_end_date(+)),",yr2,") >= '",yr1,"'
    AND sites.state_code NOT IN ('80','CC')
    AND sites.status_ind = 'P'
    AND sm.pa_parameter_code = '",par,"'
    AND COALESCE(EXTRACT(YEAR FROM sp.sampling_begin_date(+)),",yr1,") <= '",yr2,"'
    AND COALESCE(EXTRACT(YEAR FROM sp.sampling_end_date(+)),",yr2,") >= '",yr1,"'
    AND sites.state_code = seasons.cn_stt_state_code(+)
    AND (sites.county_code = seasons.cn_county_code",
        ifelse(par == 44201," OR seasons.cn_county_code IS NULL)","(+))"),"
    AND (sites.site_id = seasons.site_id",
        ifelse(par == 44201," OR seasons.site_id IS NULL)","(+))"),"
    AND COALESCE(seasons.monitoring_season_begin_year(+),",yr1,") <= '",yr2,"'
    AND COALESCE(seasons.monitoring_season_end_year(+),",yr2,") >= '",yr1,"'
    AND seasons.pa_parameter_code(+) = '",par,"'
  ORDER BY 1",sep=""))
  ## Fix issues with ozone state/county/CBSA/CSA/NAA names, collection frequencies
  if (par == 44201) {
    ## Pechanga - shorten ridiculously long name
    pechanga <- grep("Pechanga",t$naa_name_2015)
    t$naa_name_2015[pechanga] <- t$naa_name_2008[pechanga] <- t$naa_name_1997[pechanga] <-
      "Pechanga Band of Luiseno Mission Indians, CA"
    ## Seaford, DE - Fix naming issue in 2008 shapefile
    seaford <- grep("Seaford",t$naa_name_2008)
    t$naa_name_2008[seaford] <- "Seaford, DE"
    ## New York Metro Area - coastline issues for 1997 NAAQS
    nyc <- which(substr(t$id,1,5) == "09001")
    t$naa_name_1997[nyc] <- "New York-N. New Jersey-Long Island Area, NY-NJ-CT"
    ## Portland, ME - coastline issues for 1997 NAAQS
    portland <- which(substr(t$id,1,5) == "23031")
    t$naa_name_1997[portland] <- "Portland Area, ME"
    ## Fixes to state/county/CBSA/CSA names for Ozone Watch
    t$state_name <- gsub("Of","of",t$state_name)
    fix <- which(substr(t$id,1,5) == "72097")
    if (length(fix) > 0) {
      t$county_name[fix] <- "Mayaguez"
      t$cbsa_name[fix] <- "Mayaguez, PR"
      t$csa_name[fix] <- "Mayaguez-San German, PR"
    }
  }
  if (all) { monitors <- t }
  if (!all) {
    monitors <- t[which(!duplicated(t$id)),]
    first <- paste(c("monitor","nonreg","method","type","network","primary","frequency"),"begin_date",sep="_")
    last <- paste(c("monitor","nonreg","method","type","network","primary","frequency"),"end_date",sep="_")
    monitors[,first] <- lapply(t[,first],get.unique.dates,id=t$id,first=TRUE)
    monitors[,last] <- lapply(t[,last],get.unique.dates,id=t$id,first=FALSE)
    monitors$last_sample_date <- get.unique.dates(t$last_sample_date,t$id,first=FALSE)
    monitors$nonreg_concur <- get.unique.codes(t$nonreg_begin_date,t$id,t$nonreg_concur)
    monitors$method_code <- get.unique.codes(t$method_begin_date,t$id,t$method_code)
    monitors$frm_code <- get.unique.codes(t$method_begin_date,t$id,t$frm_code)
    monitors$monitor_type <- get.unique.codes(t$type_begin_date,t$id,t$monitor_type)
    monitors$network <- get.unique.codes(t$network_begin_date,t$id,t$network)
    monitors$season_begin_date <- substr(get.unique.codes(t$season_begin_date,t$id,t$season_begin_date),6,10)
    monitors$season_end_date <- substr(get.unique.codes(t$season_begin_date,t$id,t$season_end_date),6,10)
  }
  return(monitors)
}
```

```{r label="retrieve_aqs_data",echo=FALSE,message=FALSE,warning=FALSE}
## Retrieve AQS data not available in API for Exceptional Event Design Value Tool
library(plyr)
curr.year <- as.numeric(substr(as.character(Sys.Date()),1,4)) - 
ifelse(as.numeric(substr(as.character(Sys.Date()),6,7)) > 1,1,2)
o3.methods <- get.methods(par=44201)
o3.monitors <- get.monitors(par=44201,yr1=curr.year-4,yr2=curr.year,all=TRUE)
o3.seasons <- get.seasons(yr1=curr.year-4,yr2=curr.year)
pm.monitors <- get.monitors(par=88101,yr1=curr.year-4,yr2=curr.year,all=TRUE)

## Remove sites that are NAAQS excluded for the entire 5 years
o3.monitors <- subset(o3.monitors,
  as.Date(gsub(" ",paste(curr.year,"01-01",sep="-"),nonreg_begin_date)) >= as.Date(paste(curr.year-4,"01-01",sep="-")) &
  as.Date(gsub(" ",paste(curr.year,"01-01",sep="-"),nonreg_end_date)) <= as.Date(paste(curr.year,"12-31",sep="-")) &
  nonreg_concur != "Y")
pm.monitors <- subset(pm.monitors,
  as.Date(gsub(" ",paste(curr.year,"01-01",sep="-"),nonreg_begin_date)) >= as.Date(paste(curr.year-4,"01-01",sep="-")) &
  as.Date(gsub(" ",paste(curr.year,"01-01",sep="-"),nonreg_end_date)) <= as.Date(paste(curr.year,"12-31",sep="-")) &
  nonreg_concur != "Y")

## Retrieve PM2.5 site-level sample schedules
pm.schedules <- get.aqs.data(paste("SELECT DISTINCT
  ss.state_code || ss.county_code || ss.site_id AS site,
  TO_CHAR(ss.sample_day+1/24,'YYYY-MM-DD') AS sample_date
 FROM pm25_site_schedule ss
WHERE ss.parameter_code = '88101'
  AND ss.pollutant_standard_id = '22'
  AND ss.sample_day >= TO_DATE('",curr.year-4,"-01-01','YYYY-MM-DD')
  AND ss.sample_day <= TO_DATE('",curr.year,"-12-31','YYYY-MM-DD')
  AND ss.state_code NOT IN ('80','CC')
ORDER BY 1,2",sep=""))

## Retrieve PM2.5 makeup samples
makeup.samples <- get.aqs.data(paste("SELECT DISTINCT
  si.state_code || si.county_code || si.site_id AS site,
  mo.poc AS poc,
  TO_CHAR(ss.sample_day+1/24,'YYYY-MM-DD') AS sample_date,
  ss.scheduled_day_flag AS sched_ind,
  ss.creditable_day_flag AS cred_ind
 FROM monitors mo,
      pm25_scheduled_days ss,
      site_basic si
WHERE mo.si_si_id = si.si_id
  AND ss.mo_id = mo.mo_id
  AND si.state_code NOT IN ('80','CC')
  AND ss.creditable_day_flag = 'M'
  AND ss.pollutant_standard_id = '22'
  AND ss.sample_day >= TO_DATE('",curr.year-4,"-01-01','YYYY-MM-DD')
  AND ss.sample_day <= TO_DATE('",curr.year,"-12-31','YYYY-MM-DD')
  AND ss.scheduled_day_flag = 'N'
ORDER BY 1,2,3",sep=""))
pm.makeup.samples <- ddply(makeup.samples,c("site","sample_date"),
  summarize,sched_ind=sched_ind[1],cred_ind=cred_ind[1])

## Retrieve ozone hourly data regional concurrence flags
dt.begin <- paste(curr.year-4,"01-01 00:00:00",sep="-")
dt.end <- paste(curr.year+1,"01-01 06:00:00",sep="-")
o3.concurrences <- get.aqs.data(paste("SELECT DISTINCT
         rd.state_code || rd.county_code || rd.site_id || rd.poc AS id,
          TO_CHAR(rd.sampling_begin_datetime,'YYYY-MM-DD HH24:MI:SS') AS dt,
          GREATEST(rd.standard_sample_value*1000,0) AS conc,
          rd.method_code AS method,
          COALESCE(rd.event_code || rd.null_data_code,' ') AS flag,
          COALESCE(rd.event_concurence_indicator || rd.null_code_concurrence,' ') AS concur
     FROM raw_data_concurrences rd
    WHERE rd.duration_code = '1'
      AND (rd.event_code IS NOT NULL OR rd.null_data_code IS NOT NULL)
      AND rd.parameter_code = '44201'
      AND rd.sampling_begin_datetime >= TO_DATE('",dt.begin,"','YYYY-MM-DD HH24:MI:SS')
      AND rd.sampling_begin_datetime <= TO_DATE('",dt.end,"','YYYY-MM-DD HH24:MI:SS')
      AND rd.state_code NOT IN ('80','CC')
      AND (rd.event_concurence_indicator = 'Y' OR rd.null_code_concurrence = 'Y')
 ORDER BY 1,2",sep=""))

## Retrieve PM2.5 hourly data regional concurrence flags
dt.end <- paste(curr.year,"12-31 23:00:00",sep="-")
pm.concurrences.hourly <- get.aqs.data(paste("SELECT DISTINCT
          rd.state_code || rd.county_code || rd.site_id || rd.poc AS id,
          TO_CHAR(rd.sampling_begin_datetime,'YYYY-MM-DD HH24:MI:SS') AS dt,
          GREATEST(rd.standard_sample_value,0) AS conc,
          rd.method_code AS method,
          COALESCE(rd.event_code || rd.null_data_code,' ') AS flag,
          COALESCE(rd.event_concurence_indicator || rd.null_code_concurrence,' ') AS concur
     FROM raw_data_concurrences rd
    WHERE rd.duration_code = '1'
      AND (rd.event_code IS NOT NULL OR rd.null_data_code IS NOT NULL)
      AND rd.parameter_code = '88101'
      AND rd.sampling_begin_datetime >= TO_DATE('",dt.begin,"','YYYY-MM-DD HH24:MI:SS')
      AND rd.sampling_begin_datetime <= TO_DATE('",dt.end,"','YYYY-MM-DD HH24:MI:SS')
      AND rd.state_code NOT IN ('80','CC')
      AND (rd.event_concurence_indicator = 'Y' OR rd.null_code_concurrence = 'Y')
 ORDER BY 1,2",sep=""))

## Retrieve PM2.5 daily data regional concurrence flags
pm.concurrences.daily <- get.aqs.data(paste("SELECT DISTINCT
          rd.state_code || rd.county_code || rd.site_id || rd.poc AS id,
          TO_CHAR(rd.sampling_begin_datetime,'YYYY-MM-DD HH24:MI:SS') AS dt,
          GREATEST(rd.standard_sample_value,0) AS conc,
          rd.method_code AS method,
          COALESCE(rd.event_code || rd.null_data_code,' ') AS flag,
          COALESCE(rd.event_concurence_indicator || rd.null_code_concurrence,' ') AS concur
     FROM raw_data_concurrences rd
    WHERE rd.duration_code = '7'
      AND (rd.event_code IS NOT NULL OR rd.null_data_code IS NOT NULL)
      AND rd.parameter_code = '88101'
      AND rd.sampling_begin_datetime >= TO_DATE('",dt.begin,"','YYYY-MM-DD HH24:MI:SS')
      AND rd.sampling_begin_datetime <= TO_DATE('",dt.end,"','YYYY-MM-DD HH24:MI:SS')
      AND rd.state_code NOT IN ('80','CC')
      AND (rd.event_concurence_indicator = 'Y' OR rd.null_code_concurrence = 'Y')
 ORDER BY 1,2",sep=""))
```

```{r label="write_aqs_data",echo=FALSE,message=FALSE,warning=FALSE}
aqs.list <- list(o3.methods=o3.methods,o3.monitors=o3.monitors,o3.seasons=o3.seasons,pm.monitors=pm.monitors,
  pm.schedules=pm.schedules,pm.makeup.samples=pm.makeup.samples,o3.concurrences=o3.concurrences,
  pm.concurrences.hourly=pm.concurrences.hourly,pm.concurrences.daily=pm.concurrences.daily)
library(pins)
board <- pins::board_connect()
pin_write(board,x=aqs.list,name="EE_DVcalc_AQSdata",type="rds",title="AQS data for EE_DVcalc app",
  description=paste("Last updated on",Sys.Date()),versioned=FALSE)
cat("Data updated successfully at",as.character(Sys.time()))
```

